#!/bin/bash

export prefix="/Users/ankushsingh"
export dotfiles="$prefix/.dotfiles"

echo " "
echo "---------------"
echo "update dotfiles - `date +'%Y-%m-%d %H:%M:%S'`"

cd "$dotfiles"

rm -rf "$dotfiles/old/macOS"
mv "$dotfiles/macOS" "$dotfiles/old"

rm -rf "$dotfiles/macOS"
mkdir "$dotfiles/macOS"

cp -r "$prefix/.config/nvim/init.lua" "$dotfiles/macOS/init.lua"
cp -r "$prefix/.config/alacritty/alacritty.yml" "$dotfiles/macOS/alacritty.yml"
cp -r "$prefix/.config/kitty/kitty.conf" "$dotfiles/macOS/kitty.conf"
cp -r "$prefix/.zshrc" "$dotfiles/macOS/zshrc"
cp -r "$prefix/.tmux.conf" "$dotfiles/macOS/tmux.conf"
cp -r "$prefix/.p10k.zsh" "$dotfiles/macOS/p10k.zsh"
cp -r "$prefix/.config/mpv" "$dotfiles/macOS/mpv"

git add .
git commit -m "update dotfiles - `date +'%Y-%m-%d %H:%M:%S'`"
git push

echo " "
echo "done"
echo "---------------"

