#!/bin/bash

export prefix="/Users/ankush"
export dotfiles="$prefix/.dotfiles"

echo " "
echo "---------------"
echo "update dotfiles - `date +'%Y-%m-%d %H:%M:%S'`"

cd "$dotfiles"

# rm -rf "$dotfiles/old/macOS"
# mv "$dotfiles/macOS" "$dotfiles/old"

# rm -rf "$dotfiles/macOS"
# mkdir "$dotfiles/macOS"

# rsync -a -vh "$prefix/.config/nvim/init.lua" "$dotfiles/macOS/init.lua"
rsync -a -vh "$prefix/.config/nvim/lua/user/init.lua" "$dotfiles/macOS/nvim/lua/user/init.lua"
rsync -a -vh "$prefix/.config/alacritty/alacritty.yml" "$dotfiles/macOS/alacritty.yml"
rsync -a -vh "$prefix/.config/kitty/kitty.conf" "$dotfiles/macOS/kitty.conf"
rsync -a -vh "$prefix/.zshrc" "$dotfiles/macOS/zshrc"
rsync -a -vh "$prefix/.tmux.conf" "$dotfiles/macOS/tmux.conf"
rsync -a -vh "$prefix/.p10k.zsh" "$dotfiles/macOS/p10k.zsh"
rsync -a -vh "$prefix/.config/mpv" "$dotfiles/macOS"

git add .
git commit -m "update dotfiles - `date +'%Y-%m-%d %H:%M:%S'`"
git push

echo " "
echo "done"
echo "---------------"

