#!/bin/bash

export prefix="/Users/ankush"
export dotfiles="$prefix/.dotfiles"

echo " "
echo "---------------"
echo "restore dotfiles - `date +'%Y-%m-%d %H:%M:%S'`"

rsync -a -vh "$dotfiles/macOS/init.lua" "$prefix/.config/nvim/init.lua" 
# rsync -a -vh "$dotfiles/macOS/nvim/lua/user/init.lua" "$prefix/.config/nvim/lua/user/init.lua" 
rsync -a -vh "$dotfiles/macOS/alacritty.yml" "$prefix/.config/alacritty/alacritty.yml" 
rsync -a -vh "$dotfiles/macOS/kitty.conf" "$prefix/.config/kitty/kitty.conf" 
rsync -a -vh "$dotfiles/macOS/zshrc" "$prefix/.zshrc" 
rsync -a -vh "$dotfiles/macOS/tmux.conf" "$prefix/.tmux.conf" 
rsync -a -vh "$dotfiles/macOS/p10k.zsh" "$prefix/.p10k.zsh" 
rsync -a -vh  "$dotfiles/macOS/mpv" "$prefix/.config"

echo " "
echo "done"
echo "---------------"
